### PR TITLE
Upgrades of sorts

### PR DESCRIPTION
**Pull request by afkvido**
I know the CSS is shitty but I'm quite tired sorry mate, but it's a start lmao.

Other than the scuffed CSS the code structure has been completely revamped and improved, take a look!

### CODE REVIEW

**Review by Aaegis — APPROVED** [review]
Hey!

Thanks for helping me out, I'm still pretty new to web development, so I'll still try to learn some things myself.

**Review by Aaegis — APPROVED** [review]

**Comment by afkvido** [comment]
Oops uhh was only in 'draft' cuz wasn't ready for merge but whatever 😅

**Comment by afkvido** [comment]
Sure, thanks! If you'd like me to explain something, go ahead! I'll provide an explanation to anything you ask about.

**Comment by Aaegis** [comment]
Oops lmao I didnt see

**Comment by afkvido** [comment]
All good 😄

**Pull request merged**
